board/urls.py
from django.conf.urls import url
import board.views
from board.views import *


urlpatterns = [
    url(r'^$', BoardListView.as_view(), name='index'),
    url(r'^add/$', BoardCreateView.as_view(), name='add'),
    url(r'^(?P<pk>[0-9]+)/$', BoardDetailView.as_view(), name='view'),
    url(r'^(?P<pk>[0-9]+)/edit/$', BoardUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', BoardDeleteView.as_view(), name='delete'),
]

its/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from itsapp import views as user_views

import itsapp.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', itsapp.views.index, name='firstpage'),
    url(r'^join/$', itsapp.views.join, name='join'),
    url(r'^login/', auth_views.login, {'template_name': 'itsapp/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, {'template_name' : 'itsapp/logged_out.html'}, name='logout'),
    url(r'^profile/', itsapp.views.profile, name='profile'),
    url(r'^home/$', itsapp.views.home, name='home'),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'post/', include('post.urls', namespace='post')),
    url(r'oauth/', include('social_django.urls', namespace='social')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse

class Board(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자", null=True)
    title = models.CharField(max_length=50, verbose_name='제목')
    subject = models.IntegerField(verbose_name='종류')
    content = RichTextField(verbose_name='내용')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='생성일자')
    update_date = models.DateTimeField(auto_now=True, verbose_name='수정일자')


    def __str__(self):
        return f'{self.user.username} Board'
    
    def get_absolute_url(self):
        return reverse("board:index", args=(self.id,))
    


  

board/forms.py
from ckeditor.widgets import CKEditorWidget
from board.models import Board
from django.contrib.auth.models import User
from django import forms

class BoardAddForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'subject', 'content']
        exclude = ('user',)
        widgets = {
            'title' : forms.TextInput(
                attrs={
                    'class' : 'form-control form-control-lg',
                    'placeholder' : '제목',
                    'required' : True
                }
            ),
            
            'subject' : forms.Select(
                choices=(('1', '언어관련문의'), ('2' , '기기관련문의'), ('3' , '기타사항')),
                attrs={
                    'class' : 'form-control form-control-lg',
                    'placeholder': '선택해주세요',
                    'required' : True,
                }
            ),
            'content' : forms.CharField(
                widget = CKEditorWidget(
                    attrs={
                        'placeholoder' : '내용',
                    }
                )   
            ),
        }

        def __init__(self, *args, **kwargs):
            super(BoardAddForm, self).__init__(*args, **kwargs)
            

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from board.models import Board
from board.forms import BoardAddForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, FormView, DetailView
from its.views import LoginRequiredMixin
from hitcount.views import HitCountDetailView
from django.core.urlresolvers import reverse_lazy


class BoardListView(ListView):
    model = Board
    template_name = 'board/index.html'

    def get_queryset(self):
        search = self.request.GET.get('search2')
        type = self.request.GET.get('type')

        if search and type:
            if type == 'title':
                list = Board.objects.all().filter(title__contains=search)
            elif type == 'content':
                list = Board.objects.all().filter(content__contains=search)
            elif type == 'user':
                list = Board.objects.all().filter(user__username=search)
        else:
            list = Board.objects.all()
        return list.order_by('-id')



class BoardCreateView(LoginRequiredMixin, CreateView, FormView) :
    model = Board
    template_name = 'board/add.html'
    form_class = BoardAddForm
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BoardCreateView, self).form_valid(form)
    
    
class BoardUpdateView(LoginRequiredMixin, UpdateView) :
    model = Board
    template_name = 'board/add.html'
    form_class = BoardAddForm
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BoardUpdateView, self).form_valid(form)

class BoardDeleteView(LoginRequiredMixin, DeleteView) :
    model = Board
    success_url = reverse_lazy('board:index')
    template_name = 'board/delete.html'

class BoardDetailView(HitCountDetailView):
    model = Board
    template_name = 'board/view.html'
    count_hit = True

board/templates/board/add.html
{% extends 'board/layout.html' %}

{% block title %}문의사항 작성 페이지{% endblock %}

{% block script %}
    {% load static %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}


{% block content %}
    <div class="content-wrapper">
        <div class="container">
            <h3 class="card-title">문의글 생성 및 수정(작성자 : {{ user }}) </h3>
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if form.errors %}
                    <p>입력값에 오류가 있습니다.</p>
                {% endif %}
                {% for form in form %}
                <fieldset>
                    <div class="form-group">
                        {{ form }}
                    </div>
                </fieldset>
                {% endfor %}
                <div class="text-right"><input class="btn btn-outline-primary" type="submit" value="Submit"/></div>
            </form>
        </div>
    </div> 
    
{% endblock %}

board/templates/board/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}삭제 페이지{% endblock %}</title>
   {% load static %}
   {% block style %}
      <link rel="icon" type="image/png" href="{% static 'boot/images/icons/favicon.ico' %}"/>
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/bootstrap/css/bootstrap.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/fonts/iconic/css/material-design-iconic-font.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/animate/animate.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/css-hamburgers/hamburgers.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/animsition/css/animsition.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/select2/select2.min.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/vendor/daterangepicker/daterangepicker.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/css/util.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'boot/css/main.css' %}" />
   {% endblock %}
   {% block script %}
      <script src="{% static 'boot/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'boot/vendor/animsition/js/animsition.min.js' %}"></script>
      <script src="{% static 'boot/vendor/bootstrap/js/popper.js' %}"></script>
      <script src="{% static 'boot/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'boot/vendor/select2/select2.min.js' %}"></script>
      <script src="{% static 'boot/vendor/daterangepicker/moment.min.js' %}"></script>
      <script src="{% static 'boot/vendor/daterangepicker/daterangepicker.js' %}"></script>
      <script src="{% static 'boot/vendor/countdowntime/countdowntime.js' %}"></script>
      <script src="{% static 'boot/js/main.js' %}"></script>

   {% endblock %}
</head>

<body>    
   {% block content %}
   <div class="container-contact100" style="background:#f9ebc4">
      <div class="wrap-contact100">
         <form class="contact100-form validate-form" action="" method="post">
               {% csrf_token %}
            <span class="contact100-form-title">
               Do you want to delete the posts("{{ object }}")?
            </span>
            <label class="label-input100 text-center" style="color:red">주의! 삭제를 하시면 다시 복구할 수 없습니다.</label>
            <div class="container-contact100-form-btn" >
               <button class="contact100-form-btn" type="submit" value="Confirm">
                  <span>
                     Yes, I want to delete.
                     <i class="zmdi zmdi-arrow-right m-l-8"></i>
                  </span>
               </button>
            </div>
         </form>
      </div>
   </div> 
   {% endblock %}
   

</body>

board/templates/board/edit.html
{% extends 'board/layout.html' %}

{% block title %}게시물 수정하기{% endblock %}

{% load static %}
{% block script %}
    {{ block.super }}    
    {{ forms.media }}
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <div class="container">    
        <form action="{% url 'board:edit' %}" method="POST">
            {% csrf_token %}
            {% for form in forms %}
                <div class="form-group">
                    {{ form }}
                </div>
            {% endfor %}
            <div class="text-right">
                <button type="submit" class="btn btn-outline-primary">수정</button>
            </div>
        </form>
        </div>
    </div> 
{% endblock %}

board/templates/board/index.html
{% extends 'board/layout.html' %}

{% load hitcount_tags %}

{% block title %}문의사항{% endblock %}

{% block script %}
    {% load static %}
    {{ block.super }}
{% endblock %}


{% block content %}
<div class="content-wrapper">
    <div class="container">
    <table class="table table-hover">
       <thead>
            <tr class="row">
                <th class="col-md-1">번호</th>
                <th class="col-md-4">제목</th>
                <th class="col-md-2">작성자</th>
                <th class="col-md-2">생성일</th>
                <th class="col-md-1">조회수</th>
            </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            {% get_hit_count for object as total_hits %}
            <tr class="row" onclick="location.href='{% url 'board:view' object.id %}'">
                <td class="col-md-1">{{ object.id }}</td>
                <td class="col-md-4">{{ object.title }}</td>
                <td class="col-md-2">{{ object.user.username }}</td>
                <td class="col-md-2">{{ object.create_date|date:"Y-m-d" }}</td>
                <td class="col-md-1">{{ total_hits }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </table>
    <script>
        function search(type) {
            search = document.getElementById("search2").value
            location.href = "{% url 'board:index' %}?search2="+search+"&type="+type
        }
    </script>
    <div class="text-center">
        <form action="{% url 'board:index' %}" method="GET" class="form-inline">
            <div class="input-group md-1">
                <input type="text" class="form-control" id="search2" name="search2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">검색</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="javascript:search('title');">제목</a>
                        <a class="dropdown-item" href="javascript:search('content');">내용</a>
                        <a class="dropdown-item" href="javascript:search('user');">작성자</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
    </div>
    {% if user.is_authenticated %}
        <div class="text-right">
            <button tpye="button" class="btn btn-outline-primary" onclick="location.href='{% url 'board:add' %}'">글쓰기</button>
        </div>
    {% endif %}
</div>
{% endblock %}

board/templates/board/layout.html
{% extends 'layout/base.html' %}

{% block style %}
    {{ block.super }}
{% endblock %}

{% block script %}
    {{ block.super }}
{% endblock %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

board/templates/board/view.html
{% extends 'board/layout.html' %}

{% block title %}문의사항 상세보기{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <div class="container">
            <header>
                <h2>제목 : {{ object.title }}</h2>
                <div class="text-right">
                <p class="font-weight-light"><small>작성자 : {{ object.user }}<br>
                {{ object.create_date|date:'최초 작성일 : Y년 m월 d일 h시 i분 s초' }}<br>
                {{ object.update_date|date:'마지막 수정일 : Y년 m월 d일 h시 i분 s초' }}</small></p>
                </div>
            </header>
            <section>
            <p>
                {% autoescape off %}{{ object.content }}{% endautoescape %}
            </p>
            </section>
            <section>
                <div class="text-right">
                    {% if user.is_authenticated %}
                        {% if user.username == object.user.username %}
                            <button class="btn btn-outline-primary" onclick="location.href='{% url "board:edit" object.id %}'">수정</button>
                            <button class="btn btn-outline-danger" onclick="location.href='{% url "board:delete" object.id %}'">삭제</button>
                            <button class="btn btn-outline-info" onclick="location.href='{% url "board:index" %}'">목록</button>                        
                        {% else %}
                            <button class="btn btn-outline-info" onclick="location.href='{% url "board:index" %}'">목록</button>
                        {% endif %}
                    {% endif %}
                </div>
            </section>
        </div>
    </div>
{% endblock %}