its/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from itsapp import views as user_views

import itsapp.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', itsapp.views.index, name='firstpage'),
    url(r'^join/$', itsapp.views.join, name='join'),
    url(r'^login/', auth_views.login, {'template_name': 'itsapp/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, {'template_name' : 'itsapp/logged_out.html'}, name='logout'),
    url(r'^profile/', itsapp.views.profile, name='profile'),
    url(r'^home/$', itsapp.views.home, name='home'),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'post/', include('post.urls', namespace='post')),
    url(r'oauth/', include('social_django.urls', namespace='social')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from post.views import *

urlpatterns = [
    url(r'^new/$', PostCreateView.as_view(), name='new'),
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name="tagged_object_list"),
    url(r'^c_lang/', C_ListView.as_view(), name='c_list'),
    url(r'^c_plus_lang/', C_Plus_ListView.as_view(), name='c_plus_list'),
    url(r'^python_lang/', Python_ListView.as_view(), name='python_list'),
    url(r'^java_lang/', Java_ListView.as_view(), name='java_list'),
    url(r'^hp_elec/', HP_ListView.as_view(), name='hp_list'),
    url(r'^nb_elec/', NB_ListView.as_view(), name='nb_list'),
    url(r'^kb_elec/', KB_ListView.as_view(), name='kb_list'),
    url(r'^ep_elec/', EP_ListView.as_view(), name='ep_list'),
    url(r'^notice/$', AddNotice, name='add_notice'),
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView.as_view(), name='post_delete'),
    url(r'^mypost/$', My_ListView.as_view(), name='mypost'),
    url(r'^(?P<username>\w+)/list/$', Other_ListView.as_view(), name='other_list'),
    url(r'^(?P<pk>[0-9]+)/comment/$', CommentDetailView.as_view(), name='comment'),
    url(r'^(?P<pk>[0-9]+)/comment/new/$', CommentCreateView.as_view(), name='comment_new'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from ckeditor_uploader.fields import RichTextUploadingField
from itsapp.models import Language, Electronics
from PIL import Image
from tagging.fields import TagField



class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    lang_category = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True, verbose_name='언어카테고리')
    elec_category = models.ForeignKey(Electronics, on_delete=models.CASCADE, null=True, blank=True, verbose_name='기기카테고리')
    content = RichTextUploadingField(config_name='special', 
                                    external_plugin_resources=[('youtube',
                                    '/static/ckeditor/ckeditor/plugins/youtube/',
                                    'plugin.js',)], verbose_name='게시물')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='생성일자')
    tag = TagField(verbose_name='태그')

    class Meta:
        ordering = ['-create_date']
    

    def __str__(self):
        return f'{self.user.username} Post'

class Comment(models.Model) :
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} Comment'

post/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from post.models import Post
from itsapp.models import Language, Electronics
from django.contrib.auth.models import User
from multiupload.fields import MultiFileField
from tagging.fields import TagField, TagFormField
from tagging.forms import TagField
from django import forms
from django.forms import ModelForm
from .models import Comment

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['message']
        widgets = {
            'message' : forms.TextInput(
                attrs = {
                    'class' : 'form-control type_msg form-control-lg',
                    'placeholder' : 'Type your message...',
                    'style' : 'width:500px;',
                     
                }
            )
        }

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        lang_category = forms.ModelChoiceField(queryset=Language.objects.all())
        elec_category = forms.ModelChoiceField(queryset=Electronics.objects.all())
        fields = ['content', 'lang_category', 'elec_category', 'tag']
        widgets = {
            'content' : forms.CharField(
                widget = CKEditorUploadingWidget(
                    attrs={
                        'placeholoder' : '내용',
                    }
                )   
            ),
           
            'lang_category' : forms.Select(
                attrs = {
                    'class' : 'form-control form-control-lg'
                }
            ),

            'elec_category' : forms.Select(
                attrs = {
                    'class' : 'form-control form-control-lg'
                }
            ),
            'tag' : forms.TextInput(
                attrs={
                    'class' : 'form-control form-control-lg',
                    'placeholder' : '키워드를 입력해주세요.(ex : 홍길동, 화이팅)'
                }
            ),
        }
       
        def __init__(self, *args, **kwargs):
            super(PostAddForm, self).__init__(*args, **kwargs)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import FormView, ListView, TemplateView, DetailView
from django.contrib.auth.decorators import login_required
from its.views import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from post.forms import PostAddForm, CommentForm
from post.models import Post, Comment
from itsapp.models import Language, Electronics
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList
from django.core.urlresolvers import reverse

class PostCreateView(LoginRequiredMixin, CreateView, FormView) :
    model = Post
    template_name = 'post/add.html'
    form_class = PostAddForm
    success_url = reverse_lazy('post:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostListView(ListView) : 
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        search = self.request.GET.get('search')

        if search:
            post = Post.objects.all().filter(tag__contains=search)
        else:
            post = Post.objects.all()
        return post


class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'post/tagging_post_list.html'

class C_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(lang_category__language='C언어').order_by('-create_date')

class C_Plus_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(lang_category__language='C++').order_by('-create_date')

class Python_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(lang_category__language='PYTHON').order_by('-create_date')

class Java_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(lang_category__language='JAVA').order_by('-create_date')


class HP_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(elec_category__electronics='HandPhone').order_by('-create_date')

class NB_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(elec_category__electronics='NoteBook').order_by('-create_date')

class KB_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(elec_category__electronics='KeyBoard').order_by('-create_date')

class EP_ListView(ListView):
    model = Post
    template_name = 'post/list.html'

    def get_queryset(self):
        return Post.objects.all().filter(elec_category__electronics='EarPhone').order_by('-create_date')



class CommentDetailView(DetailView):
    model = Post
    template_name = 'post/comment.html'

class CommentCreateView(CreateView, FormView) :
    model = Comment
    template_name = 'post/create_comment.html'
    form_class = CommentForm

    success_url = reverse_lazy('post:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(pk=self.kwargs.get('pk'))
        return super(CommentCreateView, self).form_valid(form)

    def get_success_url(self, **kwargs) :
        return reverse('post:comment', kwargs={'pk': self.object.post.id })


def AddNotice(request):
    return render(request, 'post/add_notice.html')

class PostDeleteView(LoginRequiredMixin, DeleteView) :
    model = Post
    success_url = reverse_lazy('post:list')
    template_name = 'post/delete.html'


class My_ListView(ListView):
    model = Post
    template_name = 'post/mypost_list.html'

    def get_queryset(self):
        return Post.objects.all().filter(user=self.request.user).order_by('-create_date')

class Other_ListView(ListView):
    model = Post
    template_name = 'post/otherpost_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user
        return context
    
    def get_queryset(self, *args, **kwargs):
        post = super(Other_ListView, self).get_queryset(*args, **kwargs)
        return post.filter(user__username=self.kwargs['username'])

post/templates/post/add.html
{% extends 'post/layout2.html' %}

{% block title %}게시물 작성 페이지{% endblock %}

{% block script %}
    {% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    {{ form.media }}
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <div class="row justify-content-md-center">
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
                <p>입력값에 오류가 있습니다.</p>
            {% endif %}
            {% for form in form %}
                <div class="form-group">
                    {{ form }}
                </div>
            {% endfor %}
            <div class="text-center"><input class="btn btn-outline-primary" type="submit" value="등록하기"/></div>
        </form>
        </div>
    </div>


{% endblock %}

post/templates/post/comment.html
{% extends 'post/layout.html' %}

{% block title %}댓글 목록{% endblock %}

{% block script %}
	{% load static %}
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'bootstrap2/js2/comment.js' %}"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>

    {{ form.media }}
{% endblock %}

{% block style %} 
	{{ block.super }}

	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap2/css2/comment.css' %}" />

{% endblock %}


{% block content %}
	<div class="container-fluid h-100" style="background: #7F7FD5;
		background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
	 	background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);">
		<div class="row justify-content-center h-100">

			<div class="col-md-8 col-xl-6 chat">
				<div class="card">
					<div class="card-header msg_head">
						<div class="d-flex bd-highlight">
							<div class="img_cont">
	                            {% if object.user.profile.image %}
	                                <a href="{% url 'post:other_list' object.user.username %}"><img class="rounded-circle user_img" src="{{ object.user.profile.image.url }}"></a>
	                            {% else %}
	                               <a href="{% url 'post:other_list' object.user.username %}"><img class="rounded-circle user_img" src="{% static 'bootstrap2/images/default.png' %}"></a>
	                            {% endif %}
								<span class="online_icon"></span>
							</div>
							<div class="user_info">
								<span>{{ object.user.username }}</span>
								<p>댓글 {{ object.comment_set.all.count }}개</p>
							</div>

						</div>
						<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
						<div class="action_menu">
							<ul>
	                            <li onclick="location.href='{% url "post:other_list" object.user.username %}' "><i class="fas fa-user-circle"></i> 작성자 게시물 보기</li>
								<li onclick="location.href='{% url "post:list" %}' "><i class="fas fa-users"></i> 게시물 목록</li>
								<li onclick="location.href='{% url "post:comment_new" post.id %}' "><i class="fas fa-plus"></i> 댓글달기</li>
								<li onclick="location.href='{% url "post:list" %}' "><i class="fas fa-ban"></i> 닫기</li>
							</ul>
						</div>
					</div>
					<div class="card-body msg_card_body">
	                    {% for comment in object.comment_set.all %}
						<div class="d-flex justify-content-start mb-4">
							<div class="img_cont_msg">
								{% if comment.user.profile.image %}
									<img src="{{ comment.user.profile.image.url }}" class="rounded-circle user_img_msg">
								{% else %}
									<img src="{% static 'bootstrap2/images/default.png' %}" class="rounded-circle user_img_msg">
								{% endif %}
							</div>
							<div class="msg_cotainer">
	                            {{ comment.message }} 
	                            <span class="msg_time">
	                                {{ comment.user }}, {{ comment.created_at|date:'y-m-d' }}
								</span	>
							</div>
	                    </div>
	                    {% endfor %}                                    
					

					</div>

				</div>
			</div>
		</div>
	</div>
	</div>
{% endblock %}

post/templates/post/layout.html
{% extends 'layout/base.html' %}

{% block style %}
    {{ block.super }}
{% endblock %}

{% block script %}
    {{ block.super }}
{% endblock %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

post/templates/post/list.html
{% extends 'post/layout.html' %}

{% block title %}모든 게시물{% endblock %}

{% block style %}
	{% load static %}
    {{block.super}}

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rokkitt"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'bootstrap2/css2/list.css' %}"/>
{% endblock %}

{% block script %}
    {{block.super}}
{% endblock %}

{% block content %}
<div class="content-wrapper">
{% for post in object_list %}
	<section class="hero">
    	<div class="container">
        	<div class="row">	
				<div class="col-lg-6 offset-lg-3">
					<div class="cardbox shadow-lg bg-white">
			 			<div class="cardbox-heading">
			  				<div class="media m-0">
			   					<div class="d-flex mr-3">
			   					{% if post.user.profile.image %}
										<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{{ post.user.profile.image.url }}"></a>
			   					{% else %}
			   						<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{% static 'bootstrap2/images/default.png' %}"></a>
			   					{% endif %}
			   					</div>
			   					<div class="media-body">
			    					<p class="m-0">{{post.user.username}}</p>
									<small><span><i class="icon ion-md-pin"></i>{{ post.create_date|date:"Y-m-d D P " }}</span></small>
			   					</div>
			  				</div>
			 			</div>
			 			<div class="cardbox-item">
			  				{{ post.content|safe }}
			 			<div class="cardbox-base">
			  				<ul class="float-right">
								{% if user.username == post.user.username %}
									<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment" post.id %}'">댓글</button>

									<button class="btn btn-outline-danger btn-sm" type="submit" onclick="location.href='{% url "post:post_delete" post.id %}'">삭제</button>
								{% else %}
			   						<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment" post.id %}'">댓글</button>
								{% endif %}
			  				</ul>
			  				<ul>
			   					<li><a><i class="fa fa-thumbs-up"></i></a></li>
								{% load tagging_tags %}
								{% tags_for_object post as tags %}
								{% for tag in tags %}
			   						<li><a href="{% url 'post:tagged_object_list' tag.name %}"><span>{{ tag.name }}</span></a></li>
								{% endfor %}
							  </ul>
							  <hr>
			 			</div>
					</div>
           		</div>	
          	</div>
        </div>
    </section>
{% endfor %}
{% endblock %}

post/templates/post/mypost_list.html
{% extends 'post/layout.html' %}

{% block title %}나의 게시물{% endblock %}

{% block style %}
	{% load static %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rokkitt"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'bootstrap2/css2/list.css' %}"/>
    {{block.super}}
{% endblock %}

{% block script %}
    {{block.super}}
{% endblock %}

{% block content %}
<div class="content-wrapper">
<h2 class="text-center" style="font-family:Sans-serif; color:#00adb5;">내 게시물 모아보기</h2>
<h6 class="text-center">-{{ object_list.count}}개의 게시물-</h6>
{% for post in object_list %}
	<section class="hero">
    	<div class="container">
        	<div class="row">	
				<div class="col-lg-6 offset-lg-3">
					<div class="cardbox shadow-lg bg-white">
			 			<div class="cardbox-heading">
			  				<div class="media m-0">
			   					<div class="d-flex mr-3">
			   					{% if post.user.profile.image %}
									<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{{ post.user.profile.image.url }}"></a>
			   					{% else %}
			   						<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{% static 'bootstrap2/images/default.png' %}"></a>
			   					{% endif %}
			   					</div>
			   					<div class="media-body">
			    					<p class="m-0">{{post.user.username}}</p>
									<small><span><i class="icon ion-md-pin"></i>{{ post.create_date|date:"Y-m-d D P " }}</span></small>
			   					</div>
			  				</div>
			 			</div>
			 			<div class="cardbox-item">
			  				{{ post.content|safe }}
			 			</div>
			 			<div class="cardbox-base">
			  				<ul class="float-right">
								{% if user.username == post.user.username %}
									<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
									<button class="btn btn-outline-danger btn-sm" type="submit" onclick="location.href='{% url "post:post_delete" post.id %}'">삭제</button>
								{% else %}
			   						<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
								{% endif %}
			  				</ul>
			  				<ul>
			   					<li><a><i class="fa fa-thumbs-up"></i></a></li>
								{% load tagging_tags %}
								{% tags_for_object post as tags %}
								{% for tag in tags %}
			   						<li><a href="{% url 'post:tagged_object_list' tag.name %}"><span>{{ tag.name }}</span></a></li>
								{% endfor %}
			  				</ul>			   
			 			</div>
					</div>
           		</div>	
          	</div>
        </div>
    </section>
{% endfor %}
{% endblock %}

post/templates/post/otherpost_list.html
{% extends 'post/layout.html' %}

{% block title %}회원 게시물{% endblock %}

{% block style %}
	{% load static %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rokkitt"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'bootstrap2/css2/list.css' %}"/>
    {{block.super}}
{% endblock %}

{% block script %}
    {{block.super}}
{% endblock %}

{% block content %}
<div class="content-wrapper">
<h6 class="text-center">{{ object_list.count}}개 게시물을 보여드립니다.</h6>
{% for post in object_list %}
	<section class="hero">
    	<div class="container">
        	<div class="row">	
				<div class="col-lg-6 offset-lg-3">
					<div class="cardbox shadow-lg bg-white">
			 			<div class="cardbox-heading">
			  				<div class="media m-0">
			   					<div class="d-flex mr-3">
			   					{% if post.user.profile.image %}
									<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{{ post.user.profile.image.url }}"></a>
			   					{% else %}
			   						<a href="{% url 'post:other_list' post.user.username %}"><img class="img-fluid rounded-circle" src="{% static 'bootstrap2/images/default.png' %}"></a>
			   					{% endif %}
			   					</div>
			   					<div class="media-body">
			    					<p class="m-0">{{post.user.username}}</p>
									<small><span><i class="icon ion-md-pin"></i>{{ post.create_date|date:"Y-m-d D P " }}</span></small>
			   					</div>
			  				</div>
			 			</div>
			 			<div class="cardbox-item">
			  				{{ post.content|safe }}
			 			</div>
			 			<div class="cardbox-base">
			  				<ul class="float-right">
								{% if user.username == post.user.username %}
									<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
									<button class="btn btn-outline-danger btn-sm" type="submit" onclick="location.href='{% url "post:post_delete" post.id %}'">삭제</button>
								{% else %}
			   						<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
								{% endif %}
			  				</ul>
			  				<ul>
			   					<li><a><i class="fa fa-thumbs-up"></i></a></li>
								{% load tagging_tags %}
								{% tags_for_object post as tags %}
								{% for tag in tags %}
			   						<li><a href="{% url 'post:tagged_object_list' tag.name %}"><span>{{ tag.name }}</span></a></li>
								{% endfor %}
			  				</ul>			   
			 			</div>
					</div>
           		</div>	
          	</div>
        </div>
    </section>
{% endfor %}
{% endblock %}

post/templates/post/tagging_post_list.html
{% extends 'post/layout.html' %}

{% block title %}게시물 태그{% endblock %}

{% block style %}
	{% load static %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rokkitt"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'bootstrap2/css2/list.css' %}"/>
    {{block.super}}
{% endblock %}

{% block script %}
    {{block.super}}
{% endblock %}

{% block content %}
<br><br><br>
<h2 style="margin-left:100px; color:#6db7ca">'{{ tag.name }}' <span style="font-size:20px;">태그된 게시물</span></h2>
{% for post in object_list %}
	<section class="hero">
    	<div class="container">
        	<div class="row">	
				<div class="col-lg-6 offset-lg-3">
					<div class="cardbox shadow-lg bg-white">
			 			<div class="cardbox-heading">
			  				<div class="media m-0">
			   					<div class="d-flex mr-3">
			   					{% if post.user.profile.image %}
									<img class="img-fluid rounded-circle" src="{{ post.user.image.url }}">
			   					{% else %}
			   						<img class="img-fluid rounded-circle" src="{% static 'bootstrap2/images/default.png' %}">
			   					{% endif %}
			   					</div>
			   					<div class="media-body">
			    					<p class="m-0">{{post.user.username}}</p>
									<small><span><i class="icon ion-md-pin"></i>{{ post.create_date|date:"Y-m-d D P " }}</span></small>
			   					</div>
			  				</div>
			 			</div>
			 			<div class="cardbox-item">
			  				{{ post.content|safe }}
			 			</div>
			 			<div class="cardbox-base">
						 	<ul class="float-right">
								{% if user.username == post.user.username %}
									<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
									<button class="btn btn-outline-danger btn-sm" type="submit" onclick="location.href='{% url "post:post_delete" post.id %}'">삭제</button>
								{% else %}
			   						<button class="btn btn-outline-secondary btn-sm" type="submit" onclick="location.href='{% url "post:comment_new" post.id %}'">댓글</button>
								{% endif %}
			  				</ul>
			  				<ul>
			   					<li><a><i class="fa fa-thumbs-up"></i></a></li>
								{% load tagging_tags %}
								{% tags_for_object post as tags %}
								{% for tag in tags %}
			   					<li><a href="{% url 'post:tagged_object_list' tag.name %}"><span>{{ tag.name }}</span></a></li>
								{% endfor %}
			  				</ul>			   
			 			</div>		  
					</div>
           		</div>	
          	</div>
        </div>
    </section>
{% endfor %}
{% endblock %}